name: on-push
on:
  push:
jobs:
  build:
    runs-on:
      - ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Generate Typescript Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-fetch
          openapi-file: spec.json
          command-args: -p supportsES6=true -p npmName=awx-api-client
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: corepack enable
      - name: Use Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn
      - name: Build Typescript Client
        working-directory: typescript-fetch-client
        run: yarn install && yarn build




